version: '3.7'

networks:
  net1:
    driver: bridge


services:
    web:
        networks:
            - net1
        restart: always
        #image: sharelatex/sharelatex
        build: . 
        container_name: overleaf_sharelatex
        depends_on:
            mongo:
                condition: service_started
            redis:
                condition: service_started
            keycloak:
                condition: service_started
            ldap:
                condition: service_started
        links:
            - mongo
            - redis
        volumes:
            - ./sharelatex_data:/var/lib/sharelatex
            - ./sharelatex_packages:/usr/local/texlive
            - ./hostlog:/var/log/myapp
        environment:
            REDIS_HOST: redis
            SHARELATEX_APP_NAME: latex # change to custom name
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
            SHARELATEX_REDIS_HOST: redis
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'

            # Enables Thumbnail generation using ImageMagick
            ENABLE_CONVERSIONS: 'true'
            # Disables email confirmation requirement
            EMAIL_CONFIRMATION_DISABLED: 'true'

            SHARELATEX_ALLOW_ANONYMOUS_READ_AND_WRITE_SHARING: 'true'
            SHARELATEX_ALLOW_PUBLIC_ACCESS: 'true'

            ## This settings will work only with patched overleaf or pro version maybe?
            # ALLOW_EMAIL_LOGIN: 'true'

            LDAP_SERVER: ldap://192.168.108.154:389
            LDAP_BASE: dc=mydomain,dc=local
            LDAP_BIND_USER: cn=admin,dc=mydomain,dc=local
            LDAP_BIND_PW: admin
            SHARELATEX_SITE_URL: http://localhost:8000
            OAUTH_CLIENT_ID: oauth-ldap
            OAUTH_CLIENT_SECRET: chCpkF1rDPc16F7iqgxRZvpEsq2NdXfz
            OAUTH_AUTH_URL: http://localhost:8080/auth/realms/sharelatex/protocol/openid-connect/auth
            OAUTH_ACCESS_URL: http://keycloak:8080/auth/realms/sharelatex/protocol/openid-connect/token
            OAUTH_USER_URL: http://keycloak:8080/auth/realms/sharelatex/protocol/openid-connect/userinfo
            LDAP_CONTACTS: 'true'
            LDAP_CONTACT_FILTER: (objectClass=inetOrgPerson)
            LDAP_USER_FILTER: (mail =%m )

        ports:
            - "8000:80"

    mongo:
        restart: always
        image: mongo
        container_name: overleaf_mongo
        volumes:
            - ./mongo_data:/data/db
        ports:
            - 27017:27017
        networks:
            - net1

    redis:
        restart: always
        image: redis:5
        container_name: overleaf_redis
        volumes:
            - ./redis_data:/data
        networks:
            - net1

    keycloak:
        image: jboss/keycloak
        container_name: overleaf_keycloak
        ports:
        - "8080:8080"
        environment:
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=admin
        networks:
            - net1

    ldap:
        image: osixia/openldap:1.5.0
        container_name: overleaf_ldap
        environment:
        - LDAP_ADMIN_PASSWORD=admin
        - LDAP_DOMAIN=mydomain.local
        - LDAP_BASE_DN=dc=mydomain,dc=local
        - LDAP_TLS_VERIFY_CLIENT=never
        volumes:
        - ./ldap/ldap-data:/var/lib/ldap
        - ./ldap/ldap-config:/etc/ldap/slapd.d
        ports:
        - "389:389"
        networks:
        - net1